'use client';

import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import * as THREE from 'three';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { OutputPass } from 'three/examples/jsm/postprocessing/OutputPass.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import oscarStreamlines from './data/oscar-july-2014-streamlines.json';
import type { EarthSceneState, ScenarioId } from './science';
import { illustrativeSeaIceForYear, REGIONS, sceneScience } from './science';

// Encode range + per-scenario global-mean ΔT of the warming-pattern textures.
// Regenerated by scripts/data/build_warming_patterns.py (kept in sync manually).
const WARMING_PATTERN_META = {
  vmin: -1.0,
  vmax: 12.0,
  // Global-mean ΔT (°C, 2081–2100 vs 1995–2014) baked into each texture; used
  // to rescale the pattern to any target warming level. Filled from the JSON
  // sidecar at build time; these fallbacks match the shipped textures.
  globalMean: { ssp1_26: 1.692, ssp2_45: 2.829, ssp5_85: 5.235 } as Record<ScenarioId, number>,
} as const;

type GlobeProps = {
  scene: EarthSceneState;
  onCapability?: (ready: boolean) => void;
};

export type EarthGlobeHandle = {
  zoomIn: () => void;
  zoomOut: () => void;
  resetView: () => void;
};

type GlobeRuntime = {
  renderer: THREE.WebGLRenderer;
  composer: EffectComposer;
  bloomPass: UnrealBloomPass;
  camera: THREE.PerspectiveCamera;
  earth: THREE.Group;
  globe: THREE.Mesh<THREE.SphereGeometry, THREE.MeshStandardMaterial>;
  nightShade: THREE.Mesh<THREE.SphereGeometry, THREE.ShaderMaterial>;
  nightLights: THREE.Mesh<THREE.SphereGeometry, THREE.ShaderMaterial>;
  clouds: THREE.Mesh<THREE.SphereGeometry, THREE.MeshPhongMaterial>;
  evidence: THREE.Mesh<THREE.SphereGeometry, THREE.ShaderMaterial>;
  ice: THREE.Mesh<THREE.SphereGeometry, THREE.ShaderMaterial>;
  coast: THREE.Mesh<THREE.SphereGeometry, THREE.ShaderMaterial>;
  warmTextures: Record<ScenarioId, THREE.Texture>;
  currentStreaks: THREE.LineSegments<THREE.BufferGeometry, THREE.LineBasicMaterial>;
  currentParticles: CurrentParticle[];
  curves: THREE.CatmullRomCurve3[];
  currentSpeedFactor: number;
  targetQuaternion: THREE.Quaternion;
  targetDistance: number;
  frame: number;
  observer: ResizeObserver;
  destroy: () => void;
};

type CurrentPath = {
  name: string;
  points: [number, number, number][];
  scenarioSensitive?: boolean;
  meanSpeed: number;
};

type CurrentParticle = {
  curveIndex: number;
  progress: number;
  speed: number;
  trail: number;
  scenarioSensitive: boolean;
};

function latLon(lat: number, lon: number, radius = 1) {
  const phi = THREE.MathUtils.degToRad(lat);
  const theta = THREE.MathUtils.degToRad(lon);
  // SphereGeometry maps increasing texture U eastward onto negative Z.
  // Keep geographic longitude aligned with the equirectangular texture
  // mapping x = (lon + 180) / 360 used by makeEarthTexture().
  return new THREE.Vector3(
    radius * Math.cos(phi) * Math.cos(theta),
    radius * Math.sin(phi),
    -radius * Math.cos(phi) * Math.sin(theta),
  );
}

function focusQuaternion(lat: number, lon: number) {
  const phi = THREE.MathUtils.degToRad(lat);
  const theta = THREE.MathUtils.degToRad(lon);
  const center = latLon(lat, lon).normalize();
  const north = new THREE.Vector3(
    -Math.sin(phi) * Math.cos(theta),
    Math.cos(phi),
    Math.sin(phi) * Math.sin(theta),
  ).normalize();
  const east = new THREE.Vector3(-Math.sin(theta), 0, -Math.cos(theta)).normalize();
  // Map the local east/north/center frame to screen right/up/front. This keeps
  // the selected region centred without the arbitrary roll produced by a
  // single-vector rotation.
  const localFrame = new THREE.Matrix4().makeBasis(east, north, center);
  return new THREE.Quaternion().setFromRotationMatrix(localFrame).invert();
}

function loadColorTexture(path: string, anisotropy: number) {
  const texture = new THREE.TextureLoader().load(path);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.anisotropy = anisotropy;
  return texture;
}

const EVIDENCE_VERTEX = `
varying vec3 vNormalLocal;
varying vec3 vPositionLocal;
varying vec2 vUv;
void main() {
  vNormalLocal = normal;
  vPositionLocal = position;
  vUv = uv;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}`;

// Diverging colour ramp for temperature-change patterns (blue-white-red),
// zero anchored so no-change reads neutral. Values are °C of local ΔT.
const EVIDENCE_FRAGMENT = `
uniform sampler2D uSstMap;
uniform sampler2D uWarmLow;   // bracketing warming-pattern texture (lower GWL)
uniform sampler2D uWarmHigh;  // bracketing warming-pattern texture (higher GWL)
uniform float uWarmMix;       // 0..1 blend between the two GWL textures
uniform float uWarmLowC;      // global-mean ΔT encoded in uWarmLow (for scaling)
uniform float uWarmHighC;
uniform float uWarmScale;     // (target global ΔT) / (blended pattern global mean)
uniform float uPatVmin;       // texture decode: °C at pixel 0
uniform float uPatVmax;       // texture decode: °C at pixel 255 (well, 1.0)
uniform float uMode;
uniform float uWarming;
uniform float uTime;
uniform float uStorybook;
varying vec3 vNormalLocal;
varying vec3 vPositionLocal;
varying vec2 vUv;

vec3 divergingRamp(float t) {
  // t in 0..1, 0.5 = zero change. Cool cyan -> pale -> warm red.
  vec3 cool = vec3(0.11, 0.53, 0.86);
  vec3 mild = vec3(0.86, 0.94, 0.98);
  vec3 warm = vec3(0.98, 0.30, 0.12);
  return t < 0.5 ? mix(cool, mild, t * 2.0) : mix(mild, warm, (t - 0.5) * 2.0);
}

void main() {
  float fresnel = pow(1.0 - max(dot(normalize(vNormalLocal), vec3(0.0, 0.0, 1.0)), 0.0), 2.0);

  // Temperature-change pattern (assessed): blend the two bracketing GWL
  // textures, rescale to the target global-mean ΔT, colour with a diverging ramp.
  if (uMode < 1.5) {
    float low = texture2D(uWarmLow, vUv).r * (uPatVmax - uPatVmin) + uPatVmin;
    float high = texture2D(uWarmHigh, vUv).r * (uPatVmax - uPatVmin) + uPatVmin;
    float deltaC = mix(low, high, uWarmMix) * uWarmScale;
    float t = clamp(0.5 + deltaC / 16.0, 0.0, 1.0); // ±8°C spans the full ramp
    vec3 color = divergingRamp(t);
    float strength = clamp(abs(deltaC) / 8.0, 0.06, 1.0);
    float alpha = (0.30 + fresnel * 0.18) * strength * mix(1.0, 1.3, uStorybook);
    gl_FragColor = vec4(color, alpha);
    return;
  }

  // Observed SST texture (unchanged) for sea-surface temperature emphasis.
  vec4 observedSst = texture2D(uSstMap, vUv);
  if (uMode < 2.5) {
    if (observedSst.a < 0.04) discard;
    gl_FragColor = vec4(observedSst.rgb, observedSst.a * (0.52 + fresnel * 0.08));
    return;
  }

  float latitude = abs(normalize(vPositionLocal).y);
  vec3 level = mix(vec3(0.0, 0.78, 0.84), vec3(0.98, 0.72, 0.22), latitude * 0.6);
  vec3 sea = mix(vec3(0.0, 0.72, 0.9), vec3(0.08, 0.2, 0.5), latitude);
  vec3 color = uMode < 3.5 ? level : sea;
  float alpha = (0.20 + fresnel * 0.16) * mix(1.0, 1.35, uStorybook);
  gl_FragColor = vec4(color, alpha);
}`;

// Sea-ice: observed decadal extent morphs across 1980/2000/2010/2020/2025 for
// the past, then contracts toward the assessed ice-free threshold for the
// future (uContraction). Decadal masks are packed R/G/B/A of uIceDecades; the
// 2025 mask is uIce2025. uDecadeMix selects between two adjacent samples.
const ICE_FRAGMENT = `
uniform sampler2D uIceDecades;
uniform sampler2D uIce2025;
uniform float uDecadeA;      // 0=1980 1=2000 2=2010 3=2020 4=2025
uniform float uDecadeB;
uniform float uDecadeMix;
uniform float uContraction;  // future: latitude threshold pushing the edge poleward
uniform float uOpacity;
varying vec3 vPositionLocal;
varying vec2 vUv;
float sampleDecade(float idx) {
  vec4 packed = texture2D(uIceDecades, vUv);
  if (idx < 0.5) return packed.r;
  if (idx < 1.5) return packed.g;
  if (idx < 2.5) return packed.b;
  if (idx < 3.5) return packed.a;
  return texture2D(uIce2025, vUv).r;
}
void main() {
  float extent = mix(sampleDecade(uDecadeA), sampleDecade(uDecadeB), uDecadeMix);
  // Future contraction pushes the visible edge toward the pole without
  // inventing a shape: gate the observed 2025 mask by a latitude threshold.
  float gate = uContraction > 0.0
    ? smoothstep(uContraction - 0.03, uContraction + 0.02, normalize(vPositionLocal).y)
    : 1.0;
  float alpha = extent * gate * uOpacity;
  if (alpha < 0.02) discard;
  gl_FragColor = vec4(0.72, 0.94, 1.0, alpha);
}`;

const COAST_FRAGMENT = `
uniform sampler2D uCoastMap;
uniform float uSeaLevelM;   // assessed global mean sea-level rise, metres
varying vec3 vNormalLocal;
varying vec2 vUv;
void main() {
  float coast = texture2D(uCoastMap, vUv).r;
  float intensity = clamp(uSeaLevelM / 1.0, 0.0, 1.0);
  float fresnel = pow(1.0 - max(dot(normalize(vNormalLocal), vec3(0.0, 0.0, 1.0)), 0.0), 2.0);
  // Coastal-zone emphasis only — labelled in the UI as not an inundation map.
  float alpha = coast * intensity * (0.55 + fresnel * 0.25);
  if (alpha < 0.015) discard;
  vec3 glow = mix(vec3(0.20, 0.72, 0.95), vec3(0.98, 0.78, 0.42), intensity);
  gl_FragColor = vec4(glow, alpha);
}`;

const NIGHT_VERTEX = `
varying vec2 vUv;
varying vec3 vViewNormal;
void main() {
  vUv = uv;
  vViewNormal = normalize(normalMatrix * normal);
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}`;

const NIGHT_FRAGMENT = `
uniform sampler2D uNightMap;
uniform vec3 uLightDirection;
uniform float uIntensity;
varying vec2 vUv;
varying vec3 vViewNormal;
void main() {
  vec3 source = texture2D(uNightMap, vUv).rgb;
  float luminance = max(source.r, max(source.g, source.b));
  float nightSide = 1.0 - smoothstep(-0.14, 0.24, dot(normalize(vViewNormal), normalize(uLightDirection)));
  float alpha = nightSide * smoothstep(0.025, 0.24, luminance) * uIntensity;
  gl_FragColor = vec4(source * 3.1, alpha);
}`;

const NIGHT_SHADE_FRAGMENT = `
uniform vec3 uLightDirection;
varying vec3 vViewNormal;
void main() {
  float nightSide = 1.0 - smoothstep(-0.18, 0.26, dot(normalize(vViewNormal), normalize(uLightDirection)));
  gl_FragColor = vec4(0.004, 0.012, 0.028, nightSide * 0.90);
}`;

const ATMOSPHERE_VERTEX = `
varying vec3 vViewNormal;
void main() {
  vViewNormal = normalize(normalMatrix * normal);
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}`;

const ATMOSPHERE_FRAGMENT = `
uniform float uStrength;
varying vec3 vViewNormal;
void main() {
  float rim = pow(1.0 - abs(vViewNormal.z), 3.2);
  gl_FragColor = vec4(0.20, 0.74, 1.0, rim * uStrength);
}`;

function currentPaths(): CurrentPath[] {
  return oscarStreamlines.paths.map((path) => ({
    name: path.name,
    points: path.points as [number, number, number][],
    scenarioSensitive: /North Atlantic|Gulf Stream/.test(path.name),
    meanSpeed: path.points.reduce((sum, point) => sum + point[2], 0) / path.points.length,
  }));
}

function createRuntime(canvas: HTMLCanvasElement): GlobeRuntime {
  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true, powerPreference: 'high-performance' });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 0.72;

  const root = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(34, 1, 0.1, 100);
  camera.position.z = 4.8;
  root.add(new THREE.HemisphereLight(0x8feeff, 0x02050d, 1.45));
  const sun = new THREE.DirectionalLight(0xffe4b0, 3.2);
  sun.position.set(-3, 2, 5);
  root.add(sun);

  const starsGeometry = new THREE.BufferGeometry();
  const stars = new Float32Array(1200 * 3);
  for (let i = 0; i < 1200; i += 1) {
    const radius = 12 + Math.random() * 18;
    const theta = Math.random() * Math.PI * 2;
    const phi = Math.acos(2 * Math.random() - 1);
    stars[i * 3] = radius * Math.sin(phi) * Math.cos(theta);
    stars[i * 3 + 1] = radius * Math.cos(phi);
    stars[i * 3 + 2] = radius * Math.sin(phi) * Math.sin(theta);
  }
  starsGeometry.setAttribute('position', new THREE.BufferAttribute(stars, 3));
  root.add(new THREE.Points(starsGeometry, new THREE.PointsMaterial({ color: 0xaedfff, size: 0.025, transparent: true, opacity: 0.7 })));

  const earth = new THREE.Group();
  root.add(earth);
  const anisotropy = Math.min(8, renderer.capabilities.getMaxAnisotropy());
  const dayTexture = loadColorTexture('/earth/blue-marble-2048.png', anisotropy);
  const nightTexture = loadColorTexture('/earth/black-marble-2016-3600.jpg', anisotropy);
  const cloudTexture = loadColorTexture('/earth/clouds-2048.jpg', anisotropy);
  const sstTexture = loadColorTexture('/earth/noaa-oisst-v21-2026-08.png', anisotropy);
  const iceTexture = new THREE.TextureLoader().load('/earth/nsidc-sea-ice-extent-2025-09.png');
  iceTexture.anisotropy = anisotropy;
  const roughnessTexture = new THREE.TextureLoader().load('/earth/blue-marble-land-roughness-2048.png');
  const bumpTexture = new THREE.TextureLoader().load('/earth/blue-marble-shaded-bump-2048.jpg');
  roughnessTexture.anisotropy = anisotropy;
  bumpTexture.anisotropy = anisotropy;
  // Data-driven layers: warming patterns (per SSP), decadal sea ice, coast glow.
  const loadData = (path: string) => {
    const texture = new THREE.TextureLoader().load(path);
    texture.anisotropy = anisotropy;
    return texture;
  };
  const warmTextures: Record<ScenarioId, THREE.Texture> = {
    ssp1_26: loadData('/earth/warming-pattern-ssp1_26.png'),
    ssp2_45: loadData('/earth/warming-pattern-ssp2_45.png'),
    ssp5_85: loadData('/earth/warming-pattern-ssp5_85.png'),
  };
  const iceDecadesTexture = loadData('/earth/nsidc-sea-ice-decades.png');
  const coastTexture = loadData('/earth/coast-glow-2048.png');
  const globeMaterial = new THREE.MeshStandardMaterial({
    map: dayTexture,
    roughnessMap: roughnessTexture,
    bumpMap: bumpTexture,
    bumpScale: 0.018,
    color: 0xffffff,
    roughness: 0.76,
    metalness: 0.025,
  });
  const globe = new THREE.Mesh(new THREE.SphereGeometry(1, 128, 96), globeMaterial);
  earth.add(globe);

  // Fixed presentation lighting: intentionally reveals the terminator and is
  // disclosed in the interface as unrelated to the current solar position.
  const presentationLight = new THREE.Vector3(0.72, 0.18, 0.18).normalize();
  const nightShade = new THREE.Mesh(
    new THREE.SphereGeometry(1.0015, 128, 96),
    new THREE.ShaderMaterial({
      vertexShader: NIGHT_VERTEX,
      fragmentShader: NIGHT_SHADE_FRAGMENT,
      transparent: true,
      depthWrite: false,
      uniforms: { uLightDirection: { value: presentationLight } },
    }),
  );
  earth.add(nightShade);

  const nightLights = new THREE.Mesh(
    new THREE.SphereGeometry(1.003, 128, 96),
    new THREE.ShaderMaterial({
      vertexShader: NIGHT_VERTEX,
      fragmentShader: NIGHT_FRAGMENT,
      transparent: true,
      depthWrite: false,
      blending: THREE.AdditiveBlending,
      uniforms: {
        uNightMap: { value: nightTexture },
        uLightDirection: { value: presentationLight },
        uIntensity: { value: 1.7 },
      },
    }),
  );
  earth.add(nightLights);

  const clouds = new THREE.Mesh(
    new THREE.SphereGeometry(1.005, 128, 96),
    new THREE.MeshPhongMaterial({
      map: cloudTexture,
      alphaMap: cloudTexture,
      color: 0xeaf7ff,
      transparent: true,
      opacity: 0.28,
      depthWrite: false,
      blending: THREE.NormalBlending,
    }),
  );
  earth.add(clouds);

  const evidence = new THREE.Mesh(
    new THREE.SphereGeometry(1.012, 128, 96),
    new THREE.ShaderMaterial({
      vertexShader: EVIDENCE_VERTEX,
      fragmentShader: EVIDENCE_FRAGMENT,
      transparent: true,
      depthWrite: false,
      uniforms: {
        uSstMap: { value: sstTexture },
        uWarmLow: { value: warmTextures.ssp1_26 },
        uWarmHigh: { value: warmTextures.ssp5_85 },
        uWarmMix: { value: 0.5 },
        uWarmLowC: { value: WARMING_PATTERN_META.globalMean.ssp1_26 },
        uWarmHighC: { value: WARMING_PATTERN_META.globalMean.ssp5_85 },
        uWarmScale: { value: 1 },
        uPatVmin: { value: WARMING_PATTERN_META.vmin },
        uPatVmax: { value: WARMING_PATTERN_META.vmax },
        uMode: { value: 4 },
        uWarming: { value: 2 },
        uTime: { value: 0 },
        uStorybook: { value: 0 },
      },
    }),
  );
  earth.add(evidence);

  const ice = new THREE.Mesh(
    new THREE.SphereGeometry(1.024, 96, 64),
    new THREE.ShaderMaterial({
      vertexShader: EVIDENCE_VERTEX,
      fragmentShader: ICE_FRAGMENT,
      transparent: true,
      depthWrite: false,
      uniforms: {
        uIceDecades: { value: iceDecadesTexture },
        uIce2025: { value: iceTexture },
        uDecadeA: { value: 4 },
        uDecadeB: { value: 4 },
        uDecadeMix: { value: 0 },
        uContraction: { value: 0 },
        uOpacity: { value: 0.86 },
      },
    }),
  );
  earth.add(ice);

  const coast = new THREE.Mesh(
    new THREE.SphereGeometry(1.014, 128, 96),
    new THREE.ShaderMaterial({
      vertexShader: EVIDENCE_VERTEX,
      fragmentShader: COAST_FRAGMENT,
      transparent: true,
      depthWrite: false,
      blending: THREE.AdditiveBlending,
      uniforms: { uCoastMap: { value: coastTexture }, uSeaLevelM: { value: 0 } },
    }),
  );
  coast.visible = false;
  earth.add(coast);

  const atmosphere = new THREE.Mesh(
    new THREE.SphereGeometry(1.055, 96, 64),
    new THREE.ShaderMaterial({
      vertexShader: ATMOSPHERE_VERTEX,
      fragmentShader: ATMOSPHERE_FRAGMENT,
      transparent: true,
      depthWrite: false,
      side: THREE.BackSide,
      blending: THREE.AdditiveBlending,
      uniforms: { uStrength: { value: 0.52 } },
    }),
  );
  earth.add(atmosphere);
  const highAtmosphere = new THREE.Mesh(
    new THREE.SphereGeometry(1.095, 96, 64),
    new THREE.ShaderMaterial({
      vertexShader: ATMOSPHERE_VERTEX,
      fragmentShader: ATMOSPHERE_FRAGMENT,
      transparent: true,
      depthWrite: false,
      side: THREE.BackSide,
      blending: THREE.AdditiveBlending,
      uniforms: { uStrength: { value: 0.18 } },
    }),
  );
  earth.add(highAtmosphere);

  const paths = currentPaths();
  const curves = paths.map((path) => new THREE.CatmullRomCurve3(
    path.points.map(([lat, lon]) => latLon(lat, lon, 1.023)),
    false,
    'catmullrom',
    0.28,
  ));
  const particleCount = 1680;
  const currentGeometry = new THREE.BufferGeometry();
  currentGeometry.setAttribute('position', new THREE.BufferAttribute(new Float32Array(particleCount * 2 * 3), 3));
  const currentColors = new Float32Array(particleCount * 2 * 3);
  const currentParticles: CurrentParticle[] = [];
  const cyan = new THREE.Color(0x61f7f0);
  const gold = new THREE.Color(0xffd47a);
  for (let i = 0; i < particleCount; i += 1) {
    const curveIndex = i % curves.length;
    const progress = ((i * 0.61803398875) + (curveIndex / curves.length)) % 1;
    const observedSpeed = paths[curveIndex].meanSpeed;
    const speed = 0.018 + Math.min(0.055, observedSpeed * 0.055) + ((i * 37) % 13) / 2500;
    const trail = 0.006 + ((i * 19) % 17) / 2100;
    currentParticles.push({
      curveIndex,
      progress,
      speed,
      trail,
      scenarioSensitive: Boolean(paths[curveIndex].scenarioSensitive),
    });
    const mix = Math.min(1, paths[curveIndex].meanSpeed / 0.7);
    const head = cyan.clone().lerp(gold, mix);
    const tail = head.clone().multiplyScalar(0.16);
    currentColors.set([tail.r, tail.g, tail.b, head.r, head.g, head.b], i * 6);
  }
  currentGeometry.setAttribute('color', new THREE.BufferAttribute(currentColors, 3));
  const currentStreaks = new THREE.LineSegments(
    currentGeometry,
    new THREE.LineBasicMaterial({
      vertexColors: true,
      transparent: true,
      opacity: 0.82,
      blending: THREE.AdditiveBlending,
      depthWrite: false,
    }),
  );
  earth.add(currentStreaks);

  const composer = new EffectComposer(renderer);
  // Keep post-processing at one device pixel per CSS pixel. On Retina screens
  // this halves each bloom dimension relative to the renderer's 2x ceiling.
  composer.setPixelRatio(Math.min(1, window.devicePixelRatio));
  composer.addPass(new RenderPass(root, camera));
  const bloomPass = new UnrealBloomPass(new THREE.Vector2(1, 1), 0.42, 0.16, 1.65);
  composer.addPass(bloomPass);
  composer.addPass(new OutputPass());

  const targetQuaternion = new THREE.Quaternion();
  const observer = new ResizeObserver(() => {
    const rect = canvas.getBoundingClientRect();
    const width = Math.max(1, Math.round(rect.width));
    const height = Math.max(1, Math.round(rect.height));
    renderer.setSize(width, height, false);
    composer.setSize(width, height);
    camera.aspect = width / height;
    camera.updateProjectionMatrix();
  });
  observer.observe(canvas);

  const runtime: GlobeRuntime = {
    renderer, composer, bloomPass, camera, earth, globe, nightShade, nightLights, clouds, evidence, ice,
    coast, warmTextures,
    currentStreaks, currentParticles, curves, currentSpeedFactor: 1,
    targetQuaternion, targetDistance: 4.8, frame: 0, observer,
    destroy: () => {},
  };
  let raf = 0;
  let last = performance.now();
  const animate = (now: number) => {
    const dt = Math.min(0.05, (now - last) / 1000);
    last = now;
    if (reducedMotion) {
      runtime.earth.quaternion.copy(runtime.targetQuaternion);
      runtime.camera.position.z = runtime.targetDistance;
    } else {
      runtime.earth.quaternion.slerp(runtime.targetQuaternion, 1 - Math.pow(0.0004, dt));
      runtime.camera.position.z += (runtime.targetDistance - runtime.camera.position.z) * (1 - Math.pow(0.002, dt));
    }
    runtime.evidence.material.uniforms.uTime.value = reducedMotion ? 0 : now / 1000;
    if (!reducedMotion) runtime.clouds.rotation.y += dt * 0.012;
    const positions = runtime.currentStreaks.geometry.attributes.position as THREE.BufferAttribute;
    for (let i = 0; i < runtime.currentParticles.length; i += 1) {
      const particle = runtime.currentParticles[i];
      if (!reducedMotion) {
        const factor = particle.scenarioSensitive ? runtime.currentSpeedFactor : 1;
        const nextProgress = particle.progress + dt * particle.speed * factor;
        particle.progress = Number.isFinite(nextProgress) ? ((nextProgress % 1) + 1) % 1 : 0;
      }
      const curve = runtime.curves[particle.curveIndex];
      const headProgress = Math.min(0.999999, particle.progress);
      const tailProgress = Math.max(0, headProgress - particle.trail);
      const tail = curve.getPoint(tailProgress);
      const head = curve.getPoint(headProgress);
      positions.setXYZ(i * 2, tail.x, tail.y, tail.z);
      positions.setXYZ(i * 2 + 1, head.x, head.y, head.z);
    }
    positions.needsUpdate = true;
    composer.render();
    runtime.frame += 1;
    raf = requestAnimationFrame(animate);
  };
  raf = requestAnimationFrame(animate);
  runtime.destroy = () => {
    cancelAnimationFrame(raf);
    observer.disconnect();
    root.traverse((object) => {
      const mesh = object as THREE.Mesh;
      mesh.geometry?.dispose();
      const materials = Array.isArray(mesh.material) ? mesh.material : mesh.material ? [mesh.material] : [];
      materials.forEach((material) => material.dispose());
    });
    dayTexture.dispose();
    nightTexture.dispose();
    cloudTexture.dispose();
    sstTexture.dispose();
    iceTexture.dispose();
    roughnessTexture.dispose();
    bumpTexture.dispose();
    iceDecadesTexture.dispose();
    coastTexture.dispose();
    Object.values(warmTextures).forEach((texture) => texture.dispose());
    bloomPass.dispose();
    composer.dispose();
    renderer.dispose();
  };
  return runtime;
}

// Decade channels packed in the sea-ice texture (see build_sea_ice_decades.py).
const ICE_DECADE_YEARS = [1980, 2000, 2010, 2020, 2025];

function applyScene(runtime: GlobeRuntime, scene: EarthSceneState) {
  const region = REGIONS[scene.region];
  runtime.targetQuaternion.copy(focusQuaternion(region.lat, region.lon));
  runtime.targetDistance = region.distance;
  const science = sceneScience(scene);
  const modes = { temperature: 1, sea_ice: 2, currents: 2, sea_level: 3, coupled: 4 };
  const evidenceUniforms = runtime.evidence.material.uniforms;
  evidenceUniforms.uMode.value = modes[scene.layer];
  evidenceUniforms.uWarming.value = science.temperature.best;
  evidenceUniforms.uStorybook.value = scene.style === 'storybook' ? 1 : 0;

  // Temperature layer: pick the two SSP warming-pattern textures whose global
  // means bracket the target warming, blend, and rescale to the exact target.
  const targetWarming = science.globalWarming.value;
  const scenarios: ScenarioId[] = ['ssp1_26', 'ssp2_45', 'ssp5_85'];
  const means = scenarios.map((id) => WARMING_PATTERN_META.globalMean[id]);
  let lowIndex = 0;
  for (let i = 0; i < scenarios.length - 1; i += 1) if (targetWarming >= means[i]) lowIndex = i;
  const highIndex = Math.min(scenarios.length - 1, lowIndex + 1);
  const lowMean = means[lowIndex];
  const highMean = means[highIndex];
  const mix = highMean === lowMean ? 0 : THREE.MathUtils.clamp((targetWarming - lowMean) / (highMean - lowMean), 0, 1);
  const blendedMean = lowMean + (highMean - lowMean) * mix;
  evidenceUniforms.uWarmLow.value = runtime.warmTextures[scenarios[lowIndex]];
  evidenceUniforms.uWarmHigh.value = runtime.warmTextures[scenarios[highIndex]];
  evidenceUniforms.uWarmMix.value = mix;
  evidenceUniforms.uWarmScale.value = blendedMean > 0.05 ? targetWarming / blendedMean : 0;

  runtime.evidence.visible = scene.layer === 'temperature' || scene.layer === 'sea_level' || scene.layer === 'coupled'
    || (scene.layer === 'currents' && scene.style !== 'scientific');
  runtime.currentStreaks.visible = scene.layer === 'currents' || scene.layer === 'coupled';
  runtime.currentSpeedFactor = Math.max(0.42, 1 - science.amocDecline.best / 100);

  // Sea-level layer: coastal-zone glow scaled by assessed GMSL (not inundation).
  runtime.coast.visible = scene.layer === 'sea_level' || scene.layer === 'coupled';
  runtime.coast.material.uniforms.uSeaLevelM.value = science.seaLevel.best;

  // Sea ice: for observed years blend between decadal masks; for the future
  // hold the 2025 mask and contract the visible edge toward the pole.
  const iceUniforms = runtime.ice.material.uniforms;
  if (scene.year <= 2025) {
    let a = 0;
    for (let i = 0; i < ICE_DECADE_YEARS.length - 1; i += 1) if (scene.year >= ICE_DECADE_YEARS[i]) a = i;
    const b = Math.min(ICE_DECADE_YEARS.length - 1, a + 1);
    const span = ICE_DECADE_YEARS[b] - ICE_DECADE_YEARS[a];
    iceUniforms.uDecadeA.value = a;
    iceUniforms.uDecadeB.value = b;
    iceUniforms.uDecadeMix.value = span === 0 ? 0 : THREE.MathUtils.clamp((scene.year - ICE_DECADE_YEARS[a]) / span, 0, 1);
    iceUniforms.uContraction.value = 0;
  } else {
    const extent = illustrativeSeaIceForYear(scene.year).extent;
    const capDegrees = 7 + Math.sqrt(Math.max(0.2, extent) / 7.05) * 20;
    iceUniforms.uDecadeA.value = 4;
    iceUniforms.uDecadeB.value = 4;
    iceUniforms.uDecadeMix.value = 0;
    iceUniforms.uContraction.value = Math.sin(THREE.MathUtils.degToRad(90 - capDegrees));
  }
  runtime.ice.visible = scene.layer === 'sea_ice' || scene.layer === 'coupled';
  runtime.globe.material.roughness = scene.style === 'cinematic' ? 0.58 : 0.8;
  runtime.clouds.material.opacity = scene.style === 'scientific' ? 0.17 : scene.style === 'storybook' ? 0.34 : 0.27;
  runtime.nightLights.material.uniforms.uIntensity.value = scene.style === 'scientific' ? 0.9 : 1.25;
  runtime.currentStreaks.material.opacity = scene.style === 'scientific' ? 0.68 : 0.86;
  runtime.bloomPass.strength = scene.style === 'scientific' ? 0.4 : scene.style === 'storybook' ? 0.41 : 0.42;
  runtime.renderer.toneMappingExposure = scene.style === 'storybook' ? 0.82 : scene.style === 'scientific' ? 0.62 : 0.72;
}

const MIN_DISTANCE = 2.35;
const MAX_DISTANCE = 7.4;

function clampDistance(distance: number) {
  return THREE.MathUtils.clamp(distance, MIN_DISTANCE, MAX_DISTANCE);
}

export const EarthGlobe = forwardRef<EarthGlobeHandle, GlobeProps>(function EarthGlobe(
  { scene, onCapability },
  ref,
) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const runtimeRef = useRef<GlobeRuntime | null>(null);
  const initialSceneRef = useRef(scene);
  const latestSceneRef = useRef(scene);

  useImperativeHandle(ref, () => ({
    zoomIn: () => {
      const runtime = runtimeRef.current;
      if (runtime) runtime.targetDistance = clampDistance(runtime.targetDistance - 0.65);
    },
    zoomOut: () => {
      const runtime = runtimeRef.current;
      if (runtime) runtime.targetDistance = clampDistance(runtime.targetDistance + 0.65);
    },
    resetView: () => {
      const runtime = runtimeRef.current;
      if (runtime) applyScene(runtime, latestSceneRef.current);
    },
  }), []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    try {
      const runtime = createRuntime(canvas);
      runtimeRef.current = runtime;
      applyScene(runtime, initialSceneRef.current);

      const points = new Map<number, { x: number; y: number }>();
      const startQuaternion = new THREE.Quaternion();
      let dragOrigin = { x: 0, y: 0 };
      let pinchOrigin = 0;
      let pinchDistance = runtime.targetDistance;

      const beginSinglePointer = (point: { x: number; y: number }) => {
        dragOrigin = point;
        startQuaternion.copy(runtime.targetQuaternion);
      };
      const distanceBetweenPointers = () => {
        const [first, second] = Array.from(points.values());
        return first && second ? Math.hypot(second.x - first.x, second.y - first.y) : 0;
      };
      const onPointerDown = (event: PointerEvent) => {
        try { canvas.setPointerCapture(event.pointerId); } catch { /* Synthetic and older pointer implementations may not support capture. */ }
        points.set(event.pointerId, { x: event.clientX, y: event.clientY });
        if (points.size === 1) beginSinglePointer({ x: event.clientX, y: event.clientY });
        if (points.size === 2) {
          pinchOrigin = distanceBetweenPointers();
          pinchDistance = runtime.targetDistance;
        }
        canvas.classList.add('is-grabbing');
      };
      const onPointerMove = (event: PointerEvent) => {
        if (!points.has(event.pointerId)) return;
        points.set(event.pointerId, { x: event.clientX, y: event.clientY });
        if (points.size >= 2) {
          const nextPinch = distanceBetweenPointers();
          if (pinchOrigin > 0) runtime.targetDistance = clampDistance(pinchDistance * (pinchOrigin / nextPinch));
          return;
        }
        const deltaX = event.clientX - dragOrigin.x;
        const deltaY = event.clientY - dragOrigin.y;
        const yaw = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), deltaX * 0.006);
        const pitch = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1, 0, 0), deltaY * 0.006);
        runtime.targetQuaternion.copy(yaw.multiply(pitch).multiply(startQuaternion)).normalize();
      };
      const finishPointer = (event: PointerEvent) => {
        points.delete(event.pointerId);
        if (canvas.hasPointerCapture(event.pointerId)) canvas.releasePointerCapture(event.pointerId);
        if (points.size === 1) beginSinglePointer(Array.from(points.values())[0]);
        if (points.size === 0) canvas.classList.remove('is-grabbing');
      };
      const onWheel = (event: WheelEvent) => {
        event.preventDefault();
        runtime.targetDistance = clampDistance(runtime.targetDistance + event.deltaY * 0.004);
      };
      const onKeyDown = (event: KeyboardEvent) => {
        const rotate = (axis: THREE.Vector3, radians: number) => {
          runtime.targetQuaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(axis, radians)).normalize();
        };
        if (event.key === 'ArrowLeft') rotate(new THREE.Vector3(0, 1, 0), -0.12);
        else if (event.key === 'ArrowRight') rotate(new THREE.Vector3(0, 1, 0), 0.12);
        else if (event.key === 'ArrowUp') rotate(new THREE.Vector3(1, 0, 0), -0.12);
        else if (event.key === 'ArrowDown') rotate(new THREE.Vector3(1, 0, 0), 0.12);
        else if (event.key === '+' || event.key === '=') runtime.targetDistance = clampDistance(runtime.targetDistance - 0.55);
        else if (event.key === '-' || event.key === '_') runtime.targetDistance = clampDistance(runtime.targetDistance + 0.55);
        else if (event.key === '0' || event.key === 'Home') applyScene(runtime, latestSceneRef.current);
        else return;
        event.preventDefault();
      };

      canvas.addEventListener('pointerdown', onPointerDown);
      canvas.addEventListener('pointermove', onPointerMove);
      canvas.addEventListener('pointerup', finishPointer);
      canvas.addEventListener('pointercancel', finishPointer);
      canvas.addEventListener('wheel', onWheel, { passive: false });
      canvas.addEventListener('keydown', onKeyDown);
      onCapability?.(true);
      return () => {
        canvas.removeEventListener('pointerdown', onPointerDown);
        canvas.removeEventListener('pointermove', onPointerMove);
        canvas.removeEventListener('pointerup', finishPointer);
        canvas.removeEventListener('pointercancel', finishPointer);
        canvas.removeEventListener('wheel', onWheel);
        canvas.removeEventListener('keydown', onKeyDown);
        runtime.destroy();
        runtimeRef.current = null;
      };
    } catch (error) {
      console.error('[terra-globe]', error);
      onCapability?.(false);
    }
  }, [onCapability]);

  useEffect(() => {
    latestSceneRef.current = scene;
    if (runtimeRef.current) applyScene(runtimeRef.current, scene);
  }, [scene]);

  return <canvas ref={canvasRef} className="terra-globe" aria-label="Three-dimensional Earth visualization" role="img" tabIndex={0} />;
});
