// Adlib host-shell copy (JA/EN). One voice: a live improv stage for software.

import type { Locale } from '../i18n';

export const ADLIB_COPY = {
  ja: {
    brandTag: '言った先から、アプリになる',
    heroKicker: '即興UIランタイム',
    heroTitle: 'アプリは、実行時に生まれる。',
    heroLead: 'アプリは、',
    heroAction: '実行時に',
    heroDestination: '生まれる。',
    heroBody: 'ほしいものをひとこと伝えると、UIがその場に出現します。ボタンを押すたび、次の画面は頭脳（ブラウザのAIエージェント、またはAPI）がその場で即興します。事前に書かれたアプリコードはありません。',
    promptLabel: 'どんなアプリを出しますか？',
    promptPlaceholder: '例：飲み会の割り勘を、立て替えも含めて精算したい',
    promptButton: '舞台に上げる',
    promptBusy: '即興中…',
    examplesLabel: 'ためしに:',
    examples: ['飲み会の割り勘を精算したい', '今日のタスクを3つだけ決めるボード', '読んだ本を星で記録する棚'],
    stageEmpty: 'ここに、あなたのアプリが出現します。',
    stageBusy: '次の画面を即興しています…',
    undo: '一つ前に戻す',
    reset: '舞台を初期化',
    resetConfirm: 'この端末に保存した即興アプリを消して、最初からやり直しますか？',
    remake: '作り直す',
    brains: { webmcp: 'WebMCPエージェント', proxy: 'ダイレクトAPI', script: '台本デモ' },
    brainReady: '接続中の頭脳',
    brainNoteWebmcp: 'このページはWebMCPでツールを公開済み。ブラウザのAIに「Adlibでアプリを作って」と話しかけても操作できます。',
    brainNoteScript: 'いまは台本デモの頭脳です。ANTHROPIC_API_KEYを設定するか、WebMCP対応ブラウザで開くと本物の即興になります。',
    turn: 'ターン',
    backstage: '舞台裏',
    backstageTools: 'WebMCPツール',
    backstageEvents: '直近の操作',
    backstageState: 'アプリ状態（頭脳の記憶）',
    backstageEmpty: 'まだ操作はありません。',
    sanitizeWarn: '安全化で一部の要素を除去しました',
    errorImprov: '即興に失敗しました。前の画面を維持しています。',
    dataNote: '入力はこのブラウザとAPI経由の頭脳にのみ送られます。個人情報・機密情報は入力しないでください。',
    unsupported: 'WebMCP対応ブラウザで開くと、ブラウザ内のAIが頭脳になれます。',
    toolsRegistered: '個のツールを document.modelContext に登録済み',
  },
  en: {
    brandTag: 'Say it, and it becomes an app',
    heroKicker: 'IMPROVISED UI RUNTIME',
    heroTitle: 'Apps are born at runtime.',
    heroLead: 'Apps are born',
    heroAction: 'at',
    heroDestination: 'runtime.',
    heroBody: 'Say what you need and a UI appears. Every time you press a button, the next screen is improvised on the spot by a brain — your browser AI agent, or an API. No app code was written in advance.',
    promptLabel: 'What app should appear?',
    promptPlaceholder: 'e.g. Split a dinner bill, including who already paid',
    promptButton: 'Put it on stage',
    promptBusy: 'Improvising…',
    examplesLabel: 'Try:',
    examples: ['Split a dinner bill', 'A board to pick today’s three tasks', 'A shelf that rates books with stars'],
    stageEmpty: 'Your app will appear here.',
    stageBusy: 'Improvising the next screen…',
    undo: 'Undo one step',
    reset: 'Reset the stage',
    resetConfirm: 'Clear the improvised app saved in this browser and start over?',
    remake: 'Remake',
    brains: { webmcp: 'WebMCP agent', proxy: 'Direct API', script: 'Scripted demo' },
    brainReady: 'Connected brain',
    brainNoteWebmcp: 'This page exposes its tools over WebMCP — you can also ask your browser AI to build the app through Adlib.',
    brainNoteScript: 'Running on the scripted demo brain. Set ANTHROPIC_API_KEY or open in a WebMCP browser for real improvisation.',
    turn: 'turn',
    backstage: 'Backstage',
    backstageTools: 'WebMCP tools',
    backstageEvents: 'Recent interactions',
    backstageState: 'App state (the brain’s memory)',
    backstageEmpty: 'No interactions yet.',
    sanitizeWarn: 'Some elements were removed for safety',
    errorImprov: 'Improvisation failed; the previous screen is preserved.',
    dataNote: 'Input goes only to this browser and the API-side brain. Do not enter personal or confidential information.',
    unsupported: 'Open in a WebMCP-capable browser to let the in-browser AI be the brain.',
    toolsRegistered: 'tools registered on document.modelContext',
  },
} as const;

export type AdlibCopy = (typeof ADLIB_COPY)[Locale];
